version: "3"

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    ports:
      - "3306:3306"

  app:
    build:
      context: node
    container_name: app
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3001:3000"
    environment:
      - DBHOST=db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - nodenet
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d

networks:
  nodenet:
    driver: bridge
