version: "3"

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    ports:
      - "3306:3306"
    
  dockerize_db:
    build:
      context: ./dockerize
      dockerfile: Dockerfile.db
    container_name: dockerize_db

  app:
    build:
      context: node
    container_name: app
    networks:
      - nodenet
    #volumes:
    #  - ./node:/app
    tty: true
    ports:
      - "3001:3000"
    environment:
      - DBHOST=db
    depends_on:
      - dockerize_db

  dockerize_app:
    build:
      context: ./dockerize
      dockerfile: Dockerfile.app
    container_name: dockerize_app

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - dockerize_app
    networks:
      - nodenet
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d

networks:
  nodenet:
    driver: bridge
